name: mOStropy build checks
on: push
jobs:
  integration-tests:
    runs-on: [self-hosted, nomad]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            profile: minimal
# Rust cache temporarily disabled until issue (https://github.com/actions/cache/issues/810) is fixed
#     - uses: Swatinem/rust-cache@v2
#       with:
#         key:  "mostropy"
      - uses: actions/setup-go@v3
        with:
          go-version: '1.16.1'
      - run: cargo build --release
      - run: make reset
      - run: |
          make node > /dev/null &
          make abci > /dev/null &
          while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:26657)" != "200" ]]; do sleep 2; done
          make test
  clippy:
    runs-on: [self-hosted, nomad]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
 # Rust cache temporarily disabled until issue (https://github.com/actions/cache/issues/810) is fixed
 #     - uses: Swatinem/rust-cache@v2
 #       with:
 #         key:  "mostropy"
      - run: apt install -y clang libclang1
      - run: cargo +nightly clippy --all-targets --all-features -- -D warnings
  format:
    runs-on: [self-hosted, nomad]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: rustfmt
      - run: cargo fmt -- --check
